<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Rvl.Display.HWMonCli</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <NoWarn>CA1416,CA1873</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Rvl.Display.Core.csproj" />
  </ItemGroup>

</Project>
