; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.usb_stack = tinyusb
board_build.arduino.usb_manufacturer = denolk
board_build.arduino.usb_product = rvl-display
lib_deps = 
	adafruit/Adafruit TinyUSB Library
	bodmer/TFT_eSPI
build_flags = 
; hid config
	-D USE_TINYUSB
; tft config
  -D USER_SETUP_LOADED=1
  -D ST7735_DRIVER=1
  -D TFT_WIDTH=128
  -D TFT_HEIGHT=160
  -D TFT_MOSI=19
  -D TFT_SCLK=18
  -D TFT_CS=17
  -D TFT_DC=21
  -D TFT_RST=20
  -D TFT_BL=22
  -D ST7735_BLACKTAB=1
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=16000000
  -D LOAD_GLCD=1
  -D LOAD_GFXFF=1
